# Compilation Phase 1: Parsing

direction: right

input: "Schema Files" {
  shape: page
  style.fill: "#ea580c"
  style.stroke: "#f97316"
  style.font-color: "#ffffff"
  style.font-size: 20
}

parser: "Lexer & Parser" {
  shape: oval
  style.fill: "#9333ea"
  style.stroke: "#a855f7"
  style.font-color: "#ffffff"
  style.font-size: 20
}

output: "Type Graph" {
  shape: oval
  style.fill: "#059669"
  style.stroke: "#10b981"
  style.font-color: "#ffffff"
  style.font-size: 20
}

input -> parser: "Validate" {
  style.stroke-width: 3
  style.stroke: "#e03131"
  style.font-size: 16
  style.bold: true
  style.font-color: "#7a1616"
}

parser -> output: "Extract types" {
  style.stroke-width: 3
  style.stroke: "#a855f7"
  style.font-size: 16
  style.bold: true
  style.font-color: "#581c87"
}
