# Observer Action Types

direction: right

webhook: "Webhook" {
  shape: oval
  style.fill: "#059669"
  style.stroke: "#10b981"
  style.font-color: "#ffffff"
  style.font-size: 20
}

email: "Email" {
  shape: oval
  style.fill: "#34d399"
  style.stroke: "#10b981"
  style.font-color: "#ffffff"
  style.font-size: 20
}

slack: "Slack" {
  shape: oval
  style.fill: "#059669"
  style.stroke: "#10b981"
  style.font-color: "#ffffff"
  style.font-size: 20
}

custom: "Custom" {
  shape: oval
  style.fill: "#34d399"
  style.stroke: "#10b981"
  style.font-color: "#ffffff"
  style.font-size: 20
}
